openapi: 3.0.0
info:
  title: Amadeus OAuth2 Login
paths:
  /security/oauth2/token:
    post:
      description: >-
        The token endpoint is used by the client to obtain an access token by
        presenting its authorization grant.

        To learn more about this endpoint please refer to the specification at
        https://tools.ietf.org/html/rfc6749#section-3.2
      tags:
        - null
      summary: The OAuth 2.0 token endpoint
  /security/oauth2/token/{access_token}:
    get:
      description: Get token information
      tags:
        - null
      summary: The OAuth 2.0 token info endpoint
tags: []
