openapi: 3.0.0
info:
  title: Hotel List
paths:
  /reference-data/locations/hotels/by-hotels:
    get:
      summary: Search Hotels using its unique Id
      tags:
        - null
      description: ''
  /reference-data/locations/hotels/by-city:
    get:
      summary: Search Hotels in a city
      tags:
        - null
      description: ''
  /reference-data/locations/hotels/by-geocode:
    get:
      summary: Search Hotels using Geocode
      tags:
        - null
      description: ''
    parameters: []
tags: []
