weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-info-contact-error
    message: Contact Object
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-terms-of-service-error
    message: Terms of Service
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-description-length-error
    message: Info Description Length
  - code: openapi-no-api-in-path-error
    message: No API in Path
  - code: openapi-no-path-trailing-slash-info
    message: Path Trailing Slash
  - code: openapi-path-description-warn
    message: Path Description
  - code: openapi-version-in-path-info
    message: Version in Path
  - code: openapi-operation-security-definitions-error
    message: Operation Security Definition
  - code: openapi-request-body-on-post-error
    message: Request Body POST
  - code: openapi-operations-tags-info
    message: Operation Tags
  - code: openapi-operations-description-error
    message: Operation Description
  - code: openapi-operations-summary-info
    message: Operation Summary
  - code: openapi-operations-summary-period-none-info
    message: Operation Summary Period
  - code: openapi-operations-operation-ids-info
    message: Operation ID.
  - code: openapi-parameters-description-info
    message: Parameter Description
  - code: openapi-parameters-in-info
    message: Parameters In
  - code: openapi-parameters-name-info
    message: Parameter Name
  - code: openapi-parameters-required-error
    message: Parameters MUST have a required property.
  - code: openapi-parameters-schema-info
    message: Parameter Schema Type
  - code: openapi-parameters-schema-type-info
    message: Parameter Schema Type
  - code: openapi-response-post-404-status-code-warn
    message: 404 Status Code for POST Responses
  - code: openapi-response-get-201-content-error
    message: POST Content
  - code: openapi-response-post-201-status-code-info
    message: POST 201 Status Code
  - code: openapi-response-post-400-status-code-info
    message: 400 Status Code for POST Responses
  - code: openapi-response-post-500-status-code-info
    message: 500 Status Code for POST Responses
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-description-error
    message: Tag Descriptions
  - code: openapi-tags-name-info
    message: Tag Name
